### ISSUE TITLE
[Android 6] Privacyscreen doesn't work after locking the device

### ISSUE THREAD

**Issue by NickAdriaenssens** [devgeeks/PrivacyScreenPlugin#21]
Locking the device **when the app is opened** will cause the privacyscreen to be the last active screen from the app.

**Comment by devgeeks** [comment]
I am not sure why there seems to be these issues in Android 6.  There is almost nothing to the Android implementation. 

I'll have a look and see if I can figure out what is happening.

**Comment by NickAdriaenssens** [comment]
Thanks. It looks like it may be an Android issue https://code.google.com/p/android/issues/detail?id=202121&can=1&q=FLAG_SECURE&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

**Comment by devgeeks** [comment]
Ah. Not a lot I can do about that, sadly. Thanks for letting me know though.
