### ISSUE TITLE
[iOS] Black privacyscreen when the orientation is locked in landscape on iPhone

### ISSUE THREAD

**Issue by NickAdriaenssens** [devgeeks/PrivacyScreenPlugin#25]
When an iPhone is locked in landscape with [this plugin](https://github.com/gbenvenuti/cordova-plugin-screen-orientation) then `getImageName` will return nil.

Orientation setting for iPhone:
![image](https://cloud.githubusercontent.com/assets/5507224/16005834/b288abb4-3169-11e6-9f01-0f7e0d501568.png)

**Comment by devgeeks** [comment]
I think this has been fixed in #28 

@NickAdriaenssens is there any chance you could test this using the current master?

`cordova plugin add https://github.com/devgeeks/PrivacyScreenPlugin`

**Comment by NickAdriaenssens** [comment]
@devgeeks I seems to work!
