### ISSUE TITLE
Still can screen capture on ios

### ISSUE THREAD

**Issue by pogtdev** [devgeeks/PrivacyScreenPlugin#31]
Hi there,
I used this plug in for my app and test it both on android and ios. Android works perfectly great , no screenshot can be taken but for ios it still can screen capture.My IOS version : 8.4.1
Is there anyway to fix this?or any suggestion?

**Comment by fernandosmcit** [comment]
Hello, I'm having the same problem in IOS 9.3.2.
On Android the plugin works great, but on IOS no.

Anybody having this trouble too ?

Tks a lot.

**Comment by devgeeks** [comment]
The plugin does not prevent screen capture on iOS. That is a feature that is only on Android and is a part of the FLAG_SECURE system used in the plugin. 

To be honest, blocking screen capture is an unintended side effect on Android of my true goal which is preventing the app from being visible in the task switcher.
