### ISSUE TITLE
Splash Screen instead of black

### ISSUE THREAD

**Issue by mubasshir** [devgeeks/PrivacyScreenPlugin#32]
Can we have splash instead of black?

**Comment by devgeeks** [comment]
@mubasshir are you using the latest version (0.3.0) of the plugin? I thought that issue #11 was resolved via PR #16

**Comment by mubasshir** [comment]
I'm using version 0.3.1 on android

**Comment by devgeeks** [comment]
Oh, Android. :)

Unfortunately Android uses the built in system FLAG_SECURE functionality and the black screen is how it works. 

To get a splash screen instead would mean writing what would amount to an entire new plugin and I would rather just use the systems built in functionality. 

I might accept a PR that added this, but it would need a great deal of security review, etc.
