### ISSUE TITLE
Disable PrivacyScreen for TouchID popup

### ISSUE THREAD

**Issue by RP20** [devgeeks/PrivacyScreenPlugin#33]
I am developing app on ionic, I used PrivacyScreen Plugin to view splash screen on multitasking. But the splash screen also shown in TouchID popup, _**I want to disable this splash screen for particular screen or TouchID popup.**_

Any Idea ?

**Comment by devgeeks** [comment]
Yeah, this is a known issue. There is a PR to fix it, I just haven't had a chance to review it and merge it in... I will do as soon as I can..

PR: #30

**Comment by RP20** [comment]
Sure, Thanks for the quick response @devgeeks 👍

**Comment by nunolpz** [comment]
I actually wanted the PrivacyScreen to come up when the TouchID popup appears in an app I'm developing for OS. I've was checking the history of this to see if you have changed this so I could put it back on my own fork, but if I understood correctly, this is an iOS issue only.
Anyone have any ideas to help me?

**Comment by MobilityTiago** [comment]
Provided a fix for this that maintains behavior for previous users based on a preference set on config.xml.
In that fix you can now choose through the preference if you want privacy to show on resign or background cases only.
