### ISSUE TITLE
Not working on IOS 9.3.2 with Ionic App

### ISSUE THREAD

**Issue by fernandosmcit** [devgeeks/PrivacyScreenPlugin#35]
Hello, all.

The plugin is working fine on Android app but on IOS 9.3.2 is not working.

Anybody with this issue too?

Many thanks.
Fernando.

**Comment by devgeeks** [comment]
I saw your comment on #31

Do you mean it doesn't work at all on iOS 9.3.2, or only screen capture prevention doesn't work?

**Comment by fernandosmcit** [comment]
Only screen capture prevention does not work.
I already read your anwser in the other thread.
Tks for the fast reply!
