### ISSUE TITLE
Compile warning caused by PrivacyScreenPlugin.h header-file specified as source-file

### ISSUE THREAD

**Issue by yyfearth** [devgeeks/PrivacyScreenPlugin#38]
### Expected Behaviour

Should be compiled without warning.

### Actual Behaviour

Xcode compile the project with `warning: no rule to process file '/IOS_PROJECT/Plugins/cordova-plugin-privacyscreen/PrivacyScreenPlugin.h' of type sourcecode.c.h for architecture xxx`

### Reproduce Scenario

When compile the project using this plugin with Xcode.

#### Steps to Reproduce

Open the cordova ios project with this plugin.
Click Run or Build or Archive.
Go to the Buildtime Issues, it shows the warning as above.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Build on macOS with Xcode 8.2

#### Cordova CLI version and cordova platform version

    cordova 6.4.0
    cordova-ios 4.3.1

#### Plugin version

    cordova plugin version 0.3.1

_PR #39 is created for this issue._

**Comment by devgeeks** [comment]
I have merged this in. I'll try to get a release out with this fix in it ASAP.

**Comment by devgeeks** [comment]
Thanks so much for this...
