### ISSUE TITLE
iPhone5 (iOS 10) isn't protected from screenshot

### ISSUE THREAD

**Issue by MeteorStartup** [devgeeks/PrivacyScreenPlugin#40]
I thought PrivacyScreenPlugin applied iOS7 means iOS version(something like 10.2.1).
I tested this on iPhone 5s (10.2.1) but this wasn't work properly, and just normal screenshot works well. (but android works fine)

Is there anything I miseed? or old iPhone 5 or 6 isn't applied for this module?

What I want is just black screen or any protection from the screenshot on my app.

Thanks.

### Expected Behaviour
Screenshot isn't applied or black screen saved 
something like android does

### Actual Behaviour
Screenshot works normally on iPhone 5s (os version 10.2.1) devices 

#### Cordova CLI version and cordova platform version

    cordova --version                                    # e.g. 6.0.0
6.4.0

    cordova platform version android                     # e.g. 4.1.1

#### Plugin version

    cordova plugin version

**Comment by WuglyakBolgoink** [comment]
@MeteorStartup 

**Test**:

Device| OS | Version | Cordova | Android | iOS | BLACK-Screen available? | Can do screenshots? | Plugin work OK
---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
iPad | iOS | 10.0.2 | 6.5.0 | 4.3.1 | - | YES | YES | NO
Samsung S3 Neo | Android | 4.4.2 | 6.5.0 | - | 6.1.2 |  YES | NO | YES

**Comment by WuglyakBolgoink** [comment]
@MeteorStartup  / @devgeeks 
any news?

**Comment by WuglyakBolgoink** [comment]
**`UIApplicationUserDidTakeScreenshotNotification`** posted when the user presses the Home and Lock buttons to take a screenshot. This notification does not contain a userInfo dictionary. **This notification is posted after the screenshot is taken**.

```swift
- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.
    NSLog(@"FIRE viewDidLoad()");

    NSOperationQueue *mainQueue = [NSOperationQueue mainQueue];
    [[NSNotificationCenter defaultCenter] addObserverForName:UIApplicationUserDidTakeScreenshotNotification
                                                      object:nil
                                                       queue:mainQueue
                                                  usingBlock:^(NSNotification *note) {
                                                      // executes after screenshot
                                                      NSLog(@"FIRE UIApplicationUserDidTakeScreenshotNotification");
                                                  }];
}
```

**Comment by devgeeks** [comment]
AFAIK, blocking screenshots is not possible on iOS.

It was never an intended feature on iOS. It is only a feature in Android because it is part of the flag used to prevent the display of the paused app in the task switcher.

**Comment by WuglyakBolgoink** [comment]
ok, thank you!
