### ISSUE TITLE
SplashScreen in Android

### ISSUE THREAD

**Issue by loverdrive** [devgeeks/PrivacyScreenPlugin#43]
I used this plugin in my app, and it works, it blanks page view when it is in background (task manager is open).
I'd like to show a splashscreen in the page area, instead a white page. Is it possible for Android?

Thank you very much!

**Comment by devgeeks** [comment]
This plugin uses a built in flag in Android. It would need an entire new implementation to do this.

I'd rather just keep using the built in FLAG_SECURE even if it's not quite as pretty.
