### ISSUE TITLE
Plugin is not working on latest iOS platform

### ISSUE THREAD

**Issue by SujitSingh** [devgeeks/PrivacyScreenPlugin#50]
Great plugin. Thank you very much.
This plugin is working perfectly in all Android devices (as much as I have checked on), but same is not true for iPhone device.

### Expected Behaviour 

- Disabled/blurred screenshots in Android/iOS

### Actual Behaviour
- Able to take screenshots on iPhone (iOS 11.1.2 and iOS 11.2.2) {  }

#### Steps to Reproduce 
- Any way of taking screenshots. 

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
- iOS 11.1.2 and iOS 11.2.2

#### What device vendor (e.g. Samsung, HTC, Sony...)
- Apple

#### Cordova CLI version and cordova platform version

    cordova --version  :- 8.0.0
    cordova platform version ios :- ~4.5.4 (also checked on 4.4.0)

#### Plugin version

    cordova plugin version :- 0.3.1

List of other plugins which are included in my project - 

    cordova-plugin-app-launcher 0.4.0 "Launcher"
    cordova-plugin-appavailability 0.4.2 "AppAvailability"
    cordova-plugin-console 1.1.0 "Console"
    cordova-plugin-device 2.0.1 "Device"
    cordova-plugin-iroot 0.4.0 "iRoot"
    cordova-plugin-privacyscreen 0.3.1 "PrivacyScreenPlugin"
    cordova-plugin-splashscreen 5.0.1 "Splashscreen"
    cordova-plugin-statusbar 2.4.1 "StatusBar"
    cordova-plugin-whitelist 1.3.3 "Whitelist"
    ionic-plugin-keyboard 2.2.1 "Keyboard"

#### Sample Code that illustrates the problem
- I am uing this plugin in Ionic project. 
- Follow 5 min [official guide](https://ionicframework.com/getting-started) to start new app. 
- Add this plugin to project using [this plugin's guide](https://github.com/devgeeks/PrivacyScreenPlugin)
- Add **iOS** platform to project using - **ionic cordova platform add ios**
- Build iOS project files for Xcode - **ionic cordova build ios**
- Now using Xcode, you can emulate app in iOS emulator. 

Please let me know if I could be of any assistant.

**Comment by keinajar** [comment]
I don't believe this has ever worked in such manner on iOS, which doesn't make it a real issue as this is a plugin which main point is it "secures your app from displaying a screenshot in task switchers under Android and iOS".

Ability to block screenshots on Android is an extra feature, not the main focus of this plugin.

**Comment by wnabil** [comment]
i confirm the plugin is not working on iOS

**Comment by SujitSingh** [comment]
@keinajar I must have misunderstood this plugin's tagline. I guess I got a thick skull :smile:
