### ISSUE TITLE
InAppBrowser is closing with cordova-ios 6

### ISSUE THREAD

**Issue by Stephane84** [devgeeks/PrivacyScreenPlugin#65]
### Expected Behaviour
Building an App with cordova-ios 6, and InappBrowser, the inAppBrowser still open after background foreground change.
### Actual Behaviour
Building an App with cordova-ios 6, and InappBrowser, the inAppBrowser is closed after background foreground change.
### Reproduce Scenario (including but not limited to)
With a fresh ionic 3, 4 or 5 app, just add an InappBrowser to open a page, and plugin privacyscreen, switch the app in background and then in foreground, the inAppBrowser is closed

With cordova-ios 5.1.1 it works, on cordova-ios > 6 there is the bug

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
cordova-ios 6 on all iOS devices (no problems with android)

#### Cordova CLI version and cordova platform version

    cordova --version                                    10.0.0

#### Plugin version

0.4.0

**Comment by Stephane84** [comment]
Well, i tried this fork : https://www.npmjs.com/package/cordova-plugin-privacyscreen-storyboard
and my bug is fixed in this.

**Comment by devgeeks** [comment]
Glad you found a fork with a solution!
